services:
  - type: web
    name: business-app-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096